# Generated by Django 3.1.2 on 2020-11-17 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='books/default.jpg', upload_to='books')),
                ('dispo', models.CharField(max_length=100)),
                ('borrowed_book', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='recofremoving',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletedby', models.CharField(max_length=100)),
                ('dispo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='recordofediting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editedby', models.CharField(max_length=100)),
                ('bdispo', models.CharField(max_length=100)),
                ('tdispo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default=False, upload_to='pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addbook', models.BooleanField(default=False)),
                ('addstaff', models.BooleanField(default=False)),
                ('editbooks', models.BooleanField(default=False)),
                ('editstaff', models.BooleanField(default=False)),
                ('recofredited', models.BooleanField(default=False)),
                ('recofdeleted', models.BooleanField(default=False)),
                ('removebook', models.BooleanField(default=False)),
                ('removestaff', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='booktaken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookdispo', models.CharField(max_length=1000)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('given_at', models.DateTimeField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.borrower')),
            ],
        ),
    ]
